name: Prelease npm package
on:
  schedule:
    - cron: '0 20 * * 3,5'
  workflow_dispatch:
    inputs:
      version:
        description: '指定版本发布'
        required: false
      preid:
        description: '指定预发布版本dist-tag(alpha、beta、rc)'
        default: alpha
        required: true
      bump:
        description: '指定版本发布变更类型(premajor、preminor、prepatch)'
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

    - name: 'use check action'
      uses: ./.github/workflows/check.yml
      with:
        branch: dev

    - name: 'set username and useEmail'
      run: |
        git config user.name mengshang918
        git config user.email mengshang918@gmail.com

    - name: 'lerna command'
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        npx lerna version ${{github.event.inputs.version}} --yes --conventional-commits --conventional-prerelease --force-git-tag --no-private --no-changelog --amend --preid ${{github.event.inputs.preid}} ${{github.event.inputs.bump}} --force-publish --no-push
        # npx lerna publish from-package --yes --dist-tag ${{github.event.inputs.preid}}

