name: Release npm package
on:
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: use-check-action
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: main

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      with:
        node-version: '14'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: 'Install and build'
      run: |
        yarn
        yarn build:prod

    - name: 'set username and useEmail'
      run: |
        git config user.name mengshang918
        git config user.email mengshang918@gmail.com

    - name: 'lerna command'
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        npx lerna version --yes --conventional-commits --conventional-graduate -m "chore(release): publish @s" --force-git-tag --create-release github --no-private
        npx lerna publish from-package --yes

