name: Release npm package
on:
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch:

jobs:
  use-check-action:
    uses: JDFED/drip-form/.github/workflows/check.yml@dev
    with:
      branch: main
  publish:
    runs-on: ubuntu-latest
    needs: use-check-action
    steps:
    - name: 'lerna command'
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        npx lerna version --yes --conventional-commits --conventional-graduate -m "chore(release): publish @s" --force-git-tag --create-release github --no-private
        # npx lerna publish from-package --yes

